name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag chenxizhang/dotnet-graph-console
        docker login -u chenxizhang -p ${{secrets.DOCKER_PASSWORD}}
        docker publish chenxizhang/dotnet-graph-console
